on: push

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup android SDK
        uses: android-actions/setup-android@v2

      - name: Run bundle install
        run: |
          bundle config --global set deploy_platform_default x86_64-linux
          bundle install --jobs 4 --retry 3

      - name: Decode and create keystore file
        env:
          KEYSTORE_STRING: ${{secrets.KEYSTORE_BASE_64}}
        run: |
          FILE_PATH="${GITHUB_WORKSPACE}"/certificates
          mkdir "${FILE_PATH}"
          echo $KEYSTORE_STRING | base64 -di > "${FILE_PATH}"/keystore.jks

      - name: Decode and create Firebase app distribution key file
        env:
          FIREBASE_APP_DISTRIBUTION_KEY_STRING: ${{secrets.FIREBASE_APP_DISTRIBUTION_KEY_BASE_64}}
        run: |
          FILE_PATH="${GITHUB_WORKSPACE}"/certificates
          echo $FIREBASE_APP_DISTRIBUTION_KEY_STRING | base64 -di > "${FILE_PATH}"/firebase-app-distribution-key.json

      - name: Decode and create Firebase app distribution key file
        env:
          PLAY_STORE_APP_DISTRIBUTION_KEY_STRING: ${{secrets.PLAY_STORE_APP_DISTRIBUTION_KEY_BASE_64}}
        run: |
          FILE_PATH="${GITHUB_WORKSPACE}"/certificates
          echo $PLAY_STORE_APP_DISTRIBUTION_KEY_STRING | base64 -di > "${FILE_PATH}"/playstore-app-distribution-key.json
          ls "${FILE_PATH}"

      - name: Decode and create Google service key file
        env:
          GOOGLE_SERVICE_KEY_BASE_64: ${{secrets.GOOGLE_SERVICE_KEY_BASE_64}}
        run: |
          FILE_PATH="${GITHUB_WORKSPACE}"/app
          echo $GOOGLE_SERVICE_KEY_BASE_64 | base64 -di > "${FILE_PATH}"/google-services.json